### ISSUE TITLE
Fault code variable in EGD's state is incorrectly assigned

### ISSUE THREAD

**Issue by d-loret** [nasa-jpl/jsd#32]
The `fault_code` variable in the [EGD's state](https://github.com/nasa-jpl/jsd/blob/master/src/jsd_egd_types.h#L83-L136) is [incorrectly assigned the raw Elmo error code](https://github.com/nasa-jpl/jsd/blob/master/src/jsd_egd.c#L1315) instead of the corresponding enumeration value. This causes overflow issues of the corresponding state variable in upstream drivers such as Fastcat's Actuator where the fault_code is a `uint8` and raw Elmo error codes can be much larger than 255.

The assignment statement should be:
```
state->pub.fault_code = jsd_egd_get_fault_code_from_ec_error(error);
```

**Comment by d-loret** [comment]
@alex-brinkman @JosephBowkett , found this issue when trying interpret error codes from the Elmo.

**Comment by alex-brinkman** [comment]
> I'd rather have the fault code value itself being reported for traceability back to the ELMO docs rather than some internally defined enum (meant to just be a lookup from code -> enum -> human-readable string) . A better option would be to report the hex value of the raw error code along with the decoded string.
