### ISSUE TITLE
add EGD configuration parameter to change the analog input index

### ISSUE THREAD

**Issue by rdborn** [nasa-jpl/jsd#4]
The analog input that is available in `jsd_egd_txpdo_data_t` is currently hardcoded. It would be nice if it were configurable.
https://github.com/nasa-jpl/jsd/blob/d11a44c2197885459d26f6aad32c2bf4c4ad3ba2/src/jsd_egd_types.h#L312

**Comment by alex-brinkman** [comment]
Since this involves a change to the PDO map, it's going to be more complicated to implement. Since I haven't heard anyone else ask for this, I'm going to close it.
