### ISSUE TITLE
Discussion on Reset and Statemachine propagation

### ISSUE THREAD

**Issue by alex-brinkman** [nasa-jpl/jsd#57]
This comment is important.

The `faulted_` variable you refer there is set externally (e.g. fcat). I think what we really want here is to set `state->new_reset` to `false` at the end of the `JSD_EGD_STATE_MACHINE_STATE_FAULT` case in `jsd_egd_process_state_machine` to have the guarantee that only a `jsd_egd_reset` called *after* exiting the fault state can allow to enter the operational state.

This way we do not rely on fcat or even fastcat.

Furthermore, I think setting `state->new_reset` to `false` at the end of `jsd_egd_process_state_machine`, as in the original code, is still correct with the new changes. The outcome would be that the new reset command is effective  only when it is issued while in `JSD_EGD_STATE_MACHINE_STATE_SWITCHED_ON`, which seems like the desired behavior to me.

_Originally posted by @d-loret in https://github.com/nasa-jpl/jsd/pull/46#discussion_r1005158180_

**Comment by alex-brinkman** [comment]
> I see there is some subtlety here because the EGD state machine will not wait for a reset to exit the fault state (JSD_EGD_STATE_MACHINE_STATE_FAULT). The thing that gets latched is the error code variable.
> With respect to state->new_reset, please see my other comment above: setting it to false only at the end of this function should still be correct.
> With respect to the latching of the actual state machine state, did you consider doing that? In other words, requiring state->new_reset == true before executing the line:
> set_controlword(self, slave_id,  JSD_EGD_STATE_MACHINE_CONTROLWORD_FAULT_RESET);
> And from there, we could take any one of two approaches: 1) require an additional reset to enter Operation Enabled, or 2) use that same reset to go back into Operation Enabled (by not changing state->new_reset in SWITCH_ON_DIABLED and READY_TO_SWITCH_ON.

**Comment by alex-brinkman** [comment]
The rationale here is that the users of JSD shouldn't have to know about the state transitions internal to the EGD. The JSD EGD device is simplified to either faulted or not-faulted, and calling reset via the public API takes you from faulted to not-faulted. easy

The `new_reset` variable was introduced here to help book-keep when JSD receives a new RESET signal - This is cleared when the drive enters the STATE_MACHINE_STATE_FAULT handler, guaranteeing the properly that RESET must be called to transition to operation enabled (any only needs to be called once)

Since it's no longer cleared at the end of the process loop, this prevents clearing this input when it would be annoying and may require the application to call RESET multiple times as the drive advances through its internal statemachine.

**Comment by d-loret** [comment]
OK, thanks for the clarification.

I still think `state->new_reset` should be set to `false` at the end of the `JSD_EGD_STATE_MACHINE_STATE_FAULT` instead of `jsd_egd_update_state_from_PDO_data`. It seems to me that is the only self-sufficient way of overriding a reset command in the cycle when the fault occurs.

**Comment by alex-brinkman** [comment]
What happens if we need to wait a few cycles (up to 1sec) waiting for the EMCY to be handeled? If we clear the `new_reset` every time in the FAULT state, then any request to RESET would be overridden while we wait for the SDO exhange. 

The impact would be to require the application to call RESET at least twice, leaving users scratching their heads. Admittedly, this is quite improbable and not damaging if it does occur. This could also affect startup state determinism if say, JSD starts up in the FAULT state (I've observed this during my testing) and there's also an immediate RESET request to JSD to help reduce the impact of an idio like this.
