### ISSUE TITLE
Elmo drivers assert on validity of digital output index command

### ISSUE THREAD

**Issue by d-loret** [nasa-jpl/jsd#81]
Currently the Gold and Platinum drivers assert the validity of the digital output index when setting digital outputs:

https://github.com/nasa-jpl/jsd/blob/master/src/jsd_egd.c#L126
https://github.com/nasa-jpl/jsd/blob/master/src/jsd_epd.c#L158

This would bring the entire system down.

Since these functions are used live through Commander in the Casah stack, the probability of someone inputting an invalid index because of a typo or something else is not insignificant. The entire control system should not be brought down because of this.

A graceful handling of the situation should ignore the command and potentially notify about the error.

**Comment by preston-rogers** [comment]
I just made the modifications and tested them.
